Add model for results
greenbone/eulabeia pull request #36
Opened 2021-07-28 08:31 UTC by jjnicola

**What**:
Add GotResult and result structure.

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [x] CHANGELOG.md entry
- [ ] Documentation

2021-07-28 11:16 UTC, nichtsfrei requested changes

2021-07-28 11:16 UTC, nichtsfrei commented on models/result.go
> +	HOST_DEAD     HostStatusType = "host_dead"     // Status for a dead host
why is everything but HOST_PROGRESS lowercase?

2021-07-28 11:16 UTC, nichtsfrei commented on models/result.go
> +	Type     ResultType `json:"type"`     // Result type
`json:"type"` is clashing with `type` from message within the actual json; we need to think about either renaming: type within Message to `message_type` or this `type` to `result_type`.

2021-07-29 09:22 UTC, Kraemii approved these changes

2021-08-02 06:29 UTC, nichtsfrei submitted a review, later dismissed

2021-08-02 06:50 UTC, nichtsfrei approved these changes

2021-08-02 06:50 UTC, merged